// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQs5RxiTEw1FG8jWeses80lZhuvxQNQ-Q',
    appId: '1:240096896669:android:ee2bd9acfa88bfeb091674',
    messagingSenderId: '240096896669',
    projectId: 'tesis-backend-b2a21',
    databaseURL: 'https://tesis-backend-b2a21-default-rtdb.firebaseio.com',
    storageBucket: 'tesis-backend-b2a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV08EpwQHvuD7HCG9P6cTusD9I42Sb2cE',
    appId: '1:240096896669:ios:dbcc06c62b55a2d3091674',
    messagingSenderId: '240096896669',
    projectId: 'tesis-backend-b2a21',
    databaseURL: 'https://tesis-backend-b2a21-default-rtdb.firebaseio.com',
    storageBucket: 'tesis-backend-b2a21.appspot.com',
    iosBundleId: 'com.example.flutterDemoTesisConductor',
  );
}
